version: "3.8"
services:
  pandora:
    # image: pengzhile/pandora:1.1.15
    image: pandora_xol:1.0
    build:
      context: .
      args:
        - https_proxy=http://192.168.10.195:7890
    container_name: pandora-xol
    ports:
      - "8018:8018"
    networks:
      - frontend
    volumes:
      - db-data:/data
    environment:
      PANDORA_ACCESS_TOKEN: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJ6aGFuZ3poaS5qYW1lc0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sImh0dHBzOi8vYXBpLm9wZW5haS5jb20vYXV0aCI6eyJ1c2VyX2lkIjoidXNlci1MRXlmbjBmcURQcjcwOGtRS001Z1hGbHoifSwiaXNzIjoiaHR0cHM6Ly9hdXRoMC5vcGVuYWkuY29tLyIsInN1YiI6ImF1dGgwfDY0NTRjMTY3OGQwZjg4MDJiYjA2Y2I2YyIsImF1ZCI6WyJodHRwczovL2FwaS5vcGVuYWkuY29tL3YxIiwiaHR0cHM6Ly9vcGVuYWkub3BlbmFpLmF1dGgwYXBwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2ODk2NjQ2NjAsImV4cCI6MTY5MDg3NDI2MCwiYXpwIjoiVGRKSWNiZTE2V29USHROOTVueXl3aDVFNHlPbzZJdEciLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIG1vZGVsLnJlYWQgbW9kZWwucmVxdWVzdCBvcmdhbml6YXRpb24ucmVhZCBvcmdhbml6YXRpb24ud3JpdGUgb2ZmbGluZV9hY2Nlc3MifQ.zmosGYq1iDPBxprsafcPkeHW-iS-PAozitnceTQjaIdnMwdRWV2HIl9T5Z7PStgdgLPiMXzfX-WkWOYqQznF5oK0RFDqvYP1Stkle-QaizVGVHeQ6H0VucV2FZHrN9kocZlHOERhg4PsZ-nvH9xrG9AvoeuXJveHvyJcDVHk1bwefvBR0kXDNeVo83S-ny8LoKDAinqkGdEZKwHZiJaKA8SKNvsahpM4j5n-vd8yKSSxnOPMy3Kb8R7C-rXX799fzfIKOprDzpv8McSa3yxsZK2Cmn0nVRW7eE2icQIADGI8VQPdhyBRnC3XrD3mjexxqtt0z8BG9PkMB-3wfWMKkA"
      PANDORA_SERVER: "0.0.0.0:8018"
      PANDORA_VERBOSE:
    logging:
      driver: "local"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  frontend:


volumes:
  db-data:
